import type { Metadata } from "next";
import { Mouse_Memoirs } from "next/font/google";
import "./globals.css";

const MouseMemoirs = Mouse_Memoirs({ weight: "400", subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Hangman Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={MouseMemoirs.className}>{children}</body>
    </html>
  );
}
